// Game constants
export const TILE_SIZE = 40
export const WORLD_SIZE_MULTIPLIER = 1
export const WORLD_MAP_SIZE = 240 * WORLD_SIZE_MULTIPLIER
export const MINIMAP_VISIBLE_TILES_MOBILE = 21 * 2
export const MINIMAP_VISIBLE_TILES_DESKTOP = 33 * 2
export const MOBILE_VIEWPORT_SCALE = 1.18
export const PLAYER_SIZE = 30
export const PLAYER_HEAL_DELAY_MS = 60000
export const PLAYER_HEAL_UNDER_ROOF_MULTIPLIER = 2
export const BOMB_SIZE = 45
export const APPLE_SIZE = 15
export const SLEDGEHAMMER_SIZE = 22
export const SHOVEL_SIZE = 22
export const ENEMY_SIZE = 35
export const PLAYER_SPEED = 4
export const ENEMY_SPEED = 2
export const ENEMY_CHASE_SPEED = 3
export const ENEMY_SWIM_SPEED = 2
export const ENEMY_SPAWN_INTERVAL = 2000
export const ENEMY_RED_COLOR = "#e74c3c"
export const ENEMY_RED_SIZE = ENEMY_SIZE
export const ENEMY_RED_HEALTH = 5
export const ENEMY_RED_SPEED = ENEMY_SPEED
export const ENEMY_RED_CHASE_SPEED = ENEMY_CHASE_SPEED
export const ENEMY_RED_SWIM_SPEED = ENEMY_SWIM_SPEED
export const ENEMY_YELLOW_COLOR = "#f1c40f"
export const ENEMY_YELLOW_SIZE = 28
export const ENEMY_YELLOW_HEALTH = 4
export const ENEMY_YELLOW_SPEED = 2.35
export const ENEMY_YELLOW_CHASE_SPEED = 3.25
export const ENEMY_YELLOW_SWIM_SPEED = 2.2
export const ENEMY_BLACK_COLOR = "#111111"
export const ENEMY_BLACK_SIZE = ENEMY_SIZE * 2
export const ENEMY_BLACK_HEALTH = 12
export const ENEMY_BLACK_SPEED = 1.45
export const ENEMY_BLACK_CHASE_SPEED = 2.2
export const ENEMY_BLACK_SWIM_SPEED = 1.5
export const INITIAL_RED_ENEMY_COUNT = 4
export const INITIAL_YELLOW_ENEMY_COUNT = 2
export const INITIAL_BLACK_ENEMY_COUNT = 1
export const ENEMY_SPAWN_BATCH_RED = 2
export const ENEMY_SPAWN_BATCH_YELLOW = 1
export const ENEMY_SPAWN_BATCH_BLACK = 1
export const ENEMY_SPAWN_BATCH = ENEMY_SPAWN_BATCH_RED + ENEMY_SPAWN_BATCH_YELLOW
export const APPLE_THROW_SPEED = 8
export const ROCK_SIZE = 50 // Slightly larger than bombs
export const ROCK_COUNT = 120 // Initial number of rocks
export const WOODEN_BOX_SIZE = 45 // Size of wooden boxes
export const WOODEN_BOX_COUNT = 120 // Initial number of wooden boxes
export const WOODEN_BOX_THROW_MULTIPLIER = 0.3 // Reduced from 2 to 0.3 (4x reduction)
export const WOODEN_BOX_FLOAT_SPEED = 0.5 // How fast boxes float in water
export const WOODEN_BOX_SNAP_DISTANCE = 60 // Distance for boxes to snap to each other
export const TREE_SIZE = 44 // Canopy radius of a tree
export const TREE_HIT_POINTS = 3 // Hits needed to chop a tree down
export const TREE_MIN_SPACING = 95 // Keeps forests walkable between trunks
export const TREE_TILE_FILL_CHANCE = 0.55 // Chance a forest tile gets a tree
export const TREE_MAX_APPLES = 3 // Max apples growing on a single tree
export const TREE_APPLE_VALUE = 1 // Apples dropped from trees are worth 1
export const CAR_SIZE = 50 // Size of cars
export const BOAT_SIZE = 80 // Size of boats
export const CAR_SPEED = 8 // 2x the normal player speed (vehicles)
export const CAR_INTERACTION_RANGE = 80 // Distance for player to interact with cars
export const CAR_COUNT = 5 // Maximum number of cars in the game
export const BOAT_COUNT = 5
export const SLEDGEHAMMER_COUNT = 5
export const SHOVEL_COUNT = 5
export const INITIAL_BOMB_COUNT = 25
export const INITIAL_ENEMY_COUNT = INITIAL_RED_ENEMY_COUNT + INITIAL_YELLOW_ENEMY_COUNT
export const INITIAL_APPLE_COUNT = 40
export const APPLE_RESPAWN_THRESHOLD = 20
export const APPLE_RESPAWN_BATCH = 5
export const BOMB_RESPAWN_THRESHOLD = 20
export const BOMB_RESPAWN_BATCH = 2
export const WOODEN_BOX_RESPAWN_THRESHOLD = 15
export const WOODEN_BOX_RESPAWN_BATCH = 1
export const CHARACTER_ATTRIBUTE_BUDGET = 12
export const CAR_MAX_HEALTH = 3 // Maximum health of cars
export const CAR_MAX_SPEED = 8 // Maximum speed for cars
export const CAR_ACCELERATION = 0.25 // How quickly the car speeds up
export const CAR_DECELERATION = 0.2 // How quickly the car slows down
export const CAR_DRIFT_FACTOR = 0.85 // How much the car drifts (lower = more drift)

export const TERRAIN_TYPES = {
  WATER: 0,
  GRASS: 1,
  FOREST: 2,
  DIRT: 3,
}